# Generated by Django 6.0.7 on 2026-08-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guests',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
